### PR TITLE
add introductory text to the RTC Product Guide

### PR DESCRIPTION
**Pull request by hjkristenson**
Adding introductory context to the RTC Product Guide.

- Was thinking of adding an On-Demand subsection to the Introduction section, but I think this may be sufficient on that front. 
- Would like to also add some links/references to relevant content like the story maps and specific RTC data recipes, probably in the RTC Use Examples area of the document, but would there be merit to mentioning them up-front?

### CODE REVIEW

**Review by talogan — APPROVED** [review]
It is almost too many links!  :-)

It looks really good - lots of stuff up front.  I like it.

**Comment by talogan** [comment]
> * Was thinking of adding an On-Demand subsection to the Introduction section, but I think this may be sufficient on that front.
> * Would like to also add some links/references to relevant content like the story maps and specific RTC data recipes, probably in the RTC Use Examples area of the document, but would there be merit to mentioning them up-front?

I think it is sufficient to mention on-demand like you already have.  However, I certainly wouldn't oppose a longer introductory section.  It seems kind spares right now.

I think a link to the story map (in/near the sentence about on-demand) is a great idea!  Everybody loves the story map - I used it to teach some people about Vertex on-demand products just this last week.

**Comment by jhkennedy** [comment]
Agree it looks great. It might be nice to specify "Python SDK" however, as I think "Python" is more generally recognisable than "SDK" and gets the programmatic usage part across immediately.

**Review by talogan — APPROVED** [review]
Looks good.

**Pull request merged**
