### PR TITLE
Edit InSAR Product Guide to reflect updated displacement maps option

### PR DESCRIPTION
**Pull request by hjkristenson**
The new approach for displacement maps is to have a single option to include both maps in the product package.

Originally, the vertical displacement was included by default, but the LOS displacement was optional. Now they are both optional. 

This PR amends the InSAR Product Guide accordingly, and also fixes some unrelated errors and oversights.

### CODE REVIEW

**Review by jhkennedy — APPROVED** [review]

**Review by cirrusasf — COMMENTED** [review]
383 ....Subsidence indicated by a positive phase difference value is unintuitive when thinking about movement on the earth...

**Review by cirrusasf — COMMENTED** [review]
385 You can also directly correct the LOS Displacement map included optionally in the InSAR product package:

**Comment by hjkristenson** [comment]
> 383 ....Subsidence indicated by a positive phase difference value is unintuitive when thinking about movement on the earth...

@cirrusasf I made some different adjustments to the sentence. What do you think?

**Comment by cirrusasf** [comment]
1. The equations are Array based operation. Normally we use large letter and bold to represent the array, and use small letter to represent the scalar.  In the equations, unw_ref should be small letter, UNW*, UMW, LV_THETA, should be large letter and bold.
2. lambda constant and PI constant should have more effective digital. For example, lambda =  0.055465763 meter (https://sentinels.copernicus.eu/web/sentinel/technical-guides/sentinel-1-sar/sar-instrument). PI=3.1425926. Because we are trying to deal with the subsidence that is very small, these two constant resolution matter.

**Comment by hjkristenson** [comment]
> 1. The equations are Array based operation. Normally we use large letter and bold to represent the array, and use small letter to represent the scalar.  In the equations, unw_ref should be small letter, UNW*, UMW, LV_THETA, should be large letter and bold.
> 2. lambda constant and PI constant should have more effective digital. For example, lambda =  0.055465763 meter (https://sentinels.copernicus.eu/web/sentinel/technical-guides/sentinel-1-sar/sar-instrument). PI=3.1425926. Because we are trying to deal with the subsidence that is very small, these two constant resolution matter.

@cirrusasf I changed the ref values to small case, but I'm thinking of changing the letter from sigma to something else. Small sigma has a lot of other meanings in the SAR world, and it might be confusing. 

Is it necessary to list a value for pi? I assumed that users can choose however many digits they want to use based on their use case. 

I had changed the lv to italic; should I just use **LV** instead?

**Comment by cirrusasf** [comment]
LV_THETA is a array, better use capital letter.

**Comment by hjkristenson** [comment]
> We may not provide PI=3.1415926, but we may remind the users, because we are dealing with subsidence that is small amount, we better keep the constant with more effective digital.

I would argue that values beyond the mm scale is probably not significant. There are enough potential error sources that changes beyond the mm level would likely not be reliable. Indeed, I've seen a number of different values listed on ESA's site about what the wavelength actually is.

**Pull request merged**
