### PR TITLE
Add pixel spacing information to RTC Product Guide

### PR DESCRIPTION
**Pull request by hjkristenson**
This PR adds a section on RTC pixel spacing options to the Product Guide. It also adds pixel spacing to the default settings table.

### CODE REVIEW

**Comment by hjkristenson** [comment]
The one thing I'm not clear on is whether we actually resample the DEM *before* RTC processing the 10-m products, or if it's just that the output DEM is resampled. Maybe @asjohnston-asf or @cirrusasf would have more insight on that.

**Comment by asjohnston-asf** [comment]
We prepare the Copernicus DEM mosaic at 30m pixel spacing regardless of whether the RTC product is requested at 30m or 10m.  We hand that 30m DEM to GAMMA's `mk_geo_radcal2` program to do the RTC processing and set the `post` parameter to 30 or 10.

>     post         output image sample spacing in meters or degrees for geographic (EQA) projection
>                  NOTE: for the EQA projection, use the -z option to calculate the longitude posting to give square pixels at the
>                  center of the frame, otherwise the latitude and longitude posting are equal

`mk_geo_radcal2` outputs a "dem segment" image at the requested pixel spacing, and it's that image that we convert to a geotiff and include with the output products.

**Comment by asjohnston-asf** [comment]
When `dem_matching=False`, we call `mk_geo_radcal2` twice:
- first in `Mode 0: generate initial geocoding lookup table and simulate SAR image from DEM`
- lastly in `Mode 3: Update lookup table, generate terrain geocoded image, perform pixel area correction and generate GEOTIFF output, and calculate DEM in SAR Range-Doppler Coordinates`

I think the 10m dem segment is generated by mode 0, which is used by mode 1 to do the correction, but I wouldn't consider myself an authority on the details.

**Comment by asjohnston-asf** [comment]
Your writeup looks good to me, though, no notes.

**Review by asjohnston-asf — APPROVED** [review]

**Review by jtherrmann — APPROVED** [review]
I doubt anyone will be confused about the DEM after reading this :wink:

**Pull request merged**
