### PR TITLE
add the notebook hyp3_insar_stack_for_ts_analysis.ipynb

### PR DESCRIPTION
**Pull request by cirrusasf**

### CODE REVIEW

**Comment by forrestfwilliams** [comment]
Hey @cirrusasf, I think this looks really great!

**Comment by cirrusasf** [comment]
I write the notebook based on Joe's agu notebook. credit goes to Joe.

**Comment by jhkennedy** [comment]
@cirrusasf I based mine off the notebook you wrote in the other PR -- lots of credit for you too! I think it's fitting you're GH username will be attached to it!

**Comment by forrestfwilliams** [comment]
@cirrusasf, is this ready for review?

**Comment by cirrusasf** [comment]
Hi Forrest,

It is ready for review now.

Jiang

**Review by forrestfwilliams — APPROVED** [review]

**Comment by forrestfwilliams** [comment]
@cirrusasf looks great!

**Pull request merged**
